{{- if or .Values.serviceAccount.create .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cmcc-operator.fullname" . }}
  labels:
    {{- include "cmcc-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
{{- if .Values.cmcc.manageSecrets }}
      - secrets
{{- end }}
      - services
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'
{{- if .Values.cmcc.useCrd }}
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - "cmcc.tsystemsmms.com"
    resources:
      - coremediacontentclouds
      - coremediacontentclouds/status
    verbs:
      - get
      - list
      - update
      - watch
      - patch
{{- end }}
{{- end }}
